name: Database actions

on:
  workflow_run:
    workflows: [ Terraform init actions ]
    types:
      - completed

jobs:
  migrate_osm_script:
    name: Migrate OSM
    runs-on: ubuntu-latest
    env:
      DB_USERNAME: ${{ vars.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_ADDRESS: ${{ vars.DB_ADDRESS }}
      DB_NAME: "postgres"
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Run OSM scripts
        working-directory: ./database
        run: |
          chmod +x download-osm-ukraine.sh
          ./download-osm-ukraine.sh
        shell: bash