name: Terraform Actions

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform_validate:
    name: Terraform Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan 
          -var="db_username=${{ vars.DB_USERNAME }}"
          -var="db_password=${{ secrets.DB_PASSWORD }}"
          -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY }}"
          -var="aws_secret_key=${{ secrets.AWS_SECRET_KEY }}"
          -out=tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4.3.1
        with:
          name: terraform-plan
          path: tfplan

  terraform_apply:
    needs: terraform_validate
    name: Terraform Apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4.1.2
        with:
          name: terraform-plan
          path: .

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
