name: Terraform Actions

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform_validate:
    name: Terraform Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: "eu-west-2"

      - name: Terraform fmt
        id: fmt
        working-directory: ./terraform
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Validate
        id: validate
        working-directory: ./terraform
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        working-directory: ./terraform
        run: terraform plan
          -var="db_username=${{ vars.DB_USERNAME }}"
          -var="db_password=${{ secrets.DB_PASSWORD }}"
          -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY }}"
          -var="aws_secret_key=${{ secrets.AWS_SECRET_KEY }}"
          -out="tfplan"

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4.3.1
        with:
          name: terraform-plan
          path: terraform/tfplan

  terraform_apply:
    needs: terraform_validate
    name: Terraform Apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: "eu-west-2"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4.1.2
        with:
          name: terraform-plan
          path: tfplan

      - name: Terraform Apply
        id: apply
        working-directory: ./terraform
        run: terraform apply -auto-approve tfplan
